### ISSUE TITLE
crud fields do not display when editing crud

### ISSUE THREAD

**Issue by chorton** [laraveladminpanel/admin#21]
- Laravel Version: 5.7
- Admin Panel Version: 0.5.8
- PHP Version: 7.2
- Database Driver & Version: MySQL 5.7

### Description:

After CRUD is created via the Database Tool, the crud fields are not showing.

### Steps To Reproduce:

Create CRUD for table (fields are showing and are configurable)
Save CRUD
Edit Crud
Fields are no longer showing

![screen shot 2019-02-26 at 10 32 52 pm](https://user-images.githubusercontent.com/513859/53470568-e1976e00-3a16-11e9-928b-e66ae2b03703.png)

**Comment by alexeykostenko** [comment]
I can't reproduce your issue

**Comment by alexeykostenko** [comment]
Please try to reproduce this problem on the demo page https://demo.laraveladminpanel.com/admin
