### ISSUE TITLE
I have try to install the laraveladminpanel/admin. Its showing some error

### ISSUE THREAD

**Issue by ssboopathi1991** [laraveladminpanel/admin#6]
- Laravel Version:5.6.24
- PHP Version:7.1.3

### Description: I have try to install the laraveladminpanel/admin. Its showing some error.
I have used this command - **composer require orchestra/database ^3.5 --dev**

![capture](https://user-images.githubusercontent.com/7512019/41187931-897e2e10-6bd2-11e8-8ef6-80879aaf2661.JPG)

I have used this command - **composer require orchestra/testbench-browser-kit ^3.5 --dev**

![capture1](https://user-images.githubusercontent.com/7512019/41187948-fdae80c8-6bd2-11e8-938e-116163d8071d.JPG)

**Comment by laraveladminpanel** [comment]
I installed these packages without errors, an example of my file composer.json
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.6.*",
        "laravel/tinker": "^1.0"
    },
    "require-dev": {
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "laraveladminpanel/admin": "^0.4.0",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "orchestra/database": "^3.5",
        "orchestra/testbench-browser-kit": "^3.5",
        "phpunit/phpunit": "^7.0"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
            ]
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
