### ISSUE TITLE
DEMO version on the website not working?

### ISSUE THREAD

**Issue by shez1983** [laraveladminpanel/admin#7]
https://demo.laraveladminpanel.com/admin 

i get a whoops.. tried emailing you through the site and CONTACT US not working either..

**Comment by alexeykostenko** [comment]
Thanks for the message, I fixed the site https://demo.laraveladminpanel.com
and I fixed sending emails

пт, 7 сент. 2018 г. в 19:57, shez1983 <notifications@github.com>:

**Comment by alexeykostenko** [comment]
Thanks for the message, I fixed the site https://demo.laraveladminpanel.com and I fixed sending emails
