### ISSUE TITLE
artisan route:list error

### ISSUE THREAD

**Issue by Dzurillo** [laraveladminpanel/admin#8]
- Laravel Version: 5.6
- Admin Panel Version: latest
- PHP Version: 7.2
- Database Driver & Version:

I have problem with command:

$ php artisan route:list -v

   Symfony\Component\Debug\Exception\FatalThrowableError  : Call to a member function getActionName() on null

  at path/vendor/laraveladminpanel/admin/src/Http/Controllers/DatabaseCrudController.php:20
    16| class DatabaseCrudController extends BaseController
    17| {
    18|     public function __construct()
    19|     {
  > 20|         list(, $action) = explode('@', \Route::getCurrentRoute()->getActionName());
    21|         view()->share(compact('action'));
    22|     }
    23|

**Comment by alexeykostenko** [comment]
Thank you, Dzurillo for your message.
I fixed it and pushed it into a new version v0.5.4.

ср, 17 окт. 2018 г. в 13:38, Dzurillo <notifications@github.com>:
